#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 2
#define AUTO_MOUSE_TIME 650
#define AUTO_MOUSE_DELAY 200
#define AUTO_MOUSE_DEBOUNCE 25

#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 175
#undef FLOW_TAP_TERM
#define FLOW_TAP_TERM 150
#define CHORDAL_HOLD

#define COCOT_CPI_OPTIONS { 400, 800, 1600 }
#define COCOT_CPI_DEFAULT 2
#define COCOT_SCROLL_DIVIDERS { 1, 2, 3, 4, 5, 6 }
#define COCOT_ROTATION_ANGLE { -90, -75, -60, -45, -30, -15, 0, 15, 30, 45, 60, 75, 90 }

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 100
