// Copyright 2025 mass
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define VIAL_KEYBOARD_UID {0x03, 0x45, 0x40, 0x84, 0xB6, 0x9F, 0x23, 0xBA}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 2}
#define DYNAMIC_KEYMAP_MACRO_COUNT 255
#define DYNAMIC_MACRO_SIZE 256
#define WEAR_LEVELING_BACKING_SIZE 16384
#define DYNAMIC_KEYMAP_LAYER_COUNT 16

#define TAPPING_TERM 180
#ifndef TAPPING_TERM_PER_KEY
#define TAPPING_TERM_PER_KEY
#endif
#define QUICK_TAP_TERM 175
#undef FLOW_TAP_TERM
#define FLOW_TAP_TERM 150
#ifndef CHORDAL_HOLD
#define CHORDAL_HOLD
#endif
