#pragma once

#ifdef RGBLIGHT_ENABLE
#endif

#define TAP_CODE_DELAY 5

#define LAYER_STATE_8BIT

#ifdef DYNAMIC_KEYMAP_LAYER_COUNT
#undef DYNAMIC_KEYMAP_LAYER_COUNT
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 1
#define AUTO_MOUSE_TIME 650
#define AUTO_MOUSE_DELAY 200
#define AUTO_MOUSE_DEBOUNCE 25

#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 175
#undef FLOW_TAP_TERM
#define FLOW_TAP_TERM 150
#define CHORDAL_HOLD
